image:
  name: eu.gcr.io/savannah-emr/fls-image:20.11.20

stages:
  - test

SILThemesTests:
  stage: test
  timeout: 10 minutes
  tags:
    - healthcloud-multi
  script:
    - cd sil_themes/
    - flutter pub get
    - flutter analyze
    - flutter test --coverage test
    - genhtml -q -o coverage coverage/lcov.info
    - python3 check_coverage.py 97.00

