name: shared_themes
description: A shared library for `BeWell-Consumer` and `BeWell-Professional` that is responsible for defining and providing theme/style guidelines
version: 0.1.1
homepage: https://github.com/savannahghi/shared_themes
repository: https://github.com/savannahghi/shared_themes
issue_tracker: https://github.com/savannahghi/shared_themes/issues
documentation: https://github.com/savannahghi/shared_themes/blob/main/doc/readme.md

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^2.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  uses-material-design: true
